#!/bin/sh

OUTPUT_STYLE=${1:-compressed}

echo "node-sass with output-style of ${OUTPUT_STYLE}"

node-sass --output-style "${OUTPUT_STYLE}" --include-path scss scss/c2s/c2s.scss public/css/nhsuk.css;
node-sass --output-style "${OUTPUT_STYLE}" --include-path scss scss/c2s/c2s-print.scss public/css/print.css;
node-sass --output-style "${OUTPUT_STYLE}" --include-path scss scss/c2s/c2s-ie6.scss public/css/nhsuk-ie6.css;
node-sass --output-style "${OUTPUT_STYLE}" --include-path scss scss/c2s/c2s-ie7.scss public/css/nhsuk-ie7.css;
node-sass --output-style "${OUTPUT_STYLE}" --include-path scss scss/c2s/c2s-ie8.scss public/css/nhsuk-ie8.css;
