#!/bin/bash
# -p flag stands for --project-name and will create a different network for the test container
# so it won't interfere with the app container
docker-compose -p gp-finder-travis-test -f docker-compose-tests.yml down -v
docker-compose pull gp-finder-db
docker-compose -p gp-finder-ci-test -f docker-compose-tests.yml up -d gp-finder-db
docker-compose -p gp-finder-ci-test -f docker-compose-tests.yml build ci-tests
docker-compose -p gp-finder-ci-test -f docker-compose-tests.yml run ci-tests
