#!/bin/bash
# -p flag stands for --project-name and will create a different network for the test container
# so it won't interfere with the app container
docker-compose -p gp-finder-integration-test -f docker-compose-integration-tests.yml down -v
docker-compose pull gp-finder-db
docker-compose -p gp-finder-integration-test -f docker-compose-integration-tests.yml up --build --force-recreate tests-integration
